[project]
name = "temporal-demo"
version = "0.1.0"
description = ""
authors = [
    {name = "Saksham Shahu",email = "sakshamshahu.work@gmail.com"}
]
readme = "README.md"
requires-python = "~3.11.7"
dependencies = [
    "temporalio (>=1.11.0,<2.0.0)",
    "fastapi[standard] (>=0.115.12,<0.116.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "aiofiles (>=24.1.0,<25.0.0)",
    "pdf2image (>=1.17.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
